package frc.robot.misc;

import java.io.File;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.geometry.Pose2d;
import edu.wpi.first.wpilibj.geometry.Rotation2d;
import frc.lightning.auto.Path;
import frc.lightning.auto.SubsequentPath;

public class PathUtils {

    public static List<Pose2d> waypointsFromDeployedWaypointFile(String fname) {

        List<Pose2d> waypoints = new ArrayList<Pose2d>();

        File file = Paths.get(Filesystem.getDeployDirectory().getAbsolutePath(), "paths", fname).toFile();

        try {
            Scanner in = new Scanner(file);
            in.nextLine(); // Skip first line with "X Y Theta"
            while(in.hasNextDouble()) {
                double x = in.nextDouble();
                double y = in.nextDouble();
                double theta = in.nextDouble();
                waypoints.add(new Pose2d(x, y, Rotation2d.fromDegrees(theta)));
            }
            in.close();
        } catch (Exception e) {
            System.err.println("COULD NOT READ PATH");
            e.printStackTrace();
        }

        return waypoints;

    }

    /**
     * Reads a path from a list of waypoints generated by 
     * {@link frc.robot.commands.auto.PathConfigCommand PathConfigCommand}.
     * @param pathName Name of path object
     * @param fname Name of file in "deploy/paths/"
     * @param reversed True if the path needs to be driven backwards, false otherwise.
     * @return A {@link frc.lightning.auto.Path Path} object of the given list of waypoints.
     */
    public static Path pathFromDeployedWaypointFile(String pathName, String fname, boolean reversed) {
        return new Path(pathName, waypointsFromDeployedWaypointFile(fname), reversed);
    }

    /**
     * Reads a path from a list of waypoints generated by 
     * {@link frc.robot.commands.auto.PathConfigCommand PathConfigCommand}.
     * @param pathName Name of path object
     * @param fname Name of file in "deploy/paths/"
     * @return A {@link frc.lightning.auto.Path Path} object of the given list of waypoints.
     */
    public static Path pathFromDeployedWaypointFile(String pathName, String fname) {
        return pathFromDeployedWaypointFile(pathName, fname, false);
    }

    /**
     * Reads a path from a list of waypoints generated by 
     * {@link frc.robot.commands.auto.PathConfigCommand PathConfigCommand}.
     * @param pathName Name of path object
     * @param fname Name of file in "deploy/paths/"
     * @param reversed True if the path needs to be driven backwards, false otherwise.
     * @return A {@link frc.lightning.auto.SubsequentPath SubsequentPath} object of the given list of waypoints.
     */
    public static SubsequentPath subsequentPathFromDeployedWaypointFile(String pathName, String fname, boolean reversed) {
        return new SubsequentPath(pathName, waypointsFromDeployedWaypointFile(fname), reversed);
    }

    /**
     * Reads a path from a list of waypoints generated by 
     * {@link frc.robot.commands.auto.PathConfigCommand PathConfigCommand}.
     * @param pathName Name of path object
     * @param fname Name of file in "deploy/paths/"
     * @return A {@link frc.lightning.auto.SubsequentPath SubsequentPath} object of the given list of waypoints.
     */
    public static SubsequentPath subsequentPathFromDeployedWaypointFile(String pathName, String fname) {
        return subsequentPathFromDeployedWaypointFile(pathName, fname, false);
    }

}
